import Image from "next/image";
import { DesignModels } from "@/components/design-models";
import { IntroLoader } from "@/components/intro-loader";
import { LuuConsultant } from "@/components/luu-consultant";
import { QuoteForm } from "@/components/quote-form";
import { Services } from "@/components/services";
import { services } from "@/lib/editorial-content";

const rooms = [["Living rooms", "/media/rooms/living-room.png", "50% 50%"], ["Kitchens", "/media/rooms/kitchen.png", "50% 50%"], ["Bedrooms", "/media/rooms/bedroom.png", "50% 45%"], ["Bathrooms", "/media/rooms/bathroom.jpeg", "50% 50%"]] as const;
const projects = [["The Morning Room", "Residential Interiors", "A warm, open living space shaped around everyday rituals and natural light.", "/media/home/hero.jpeg", "50% 50%"], ["Gathered Kitchen", "Kitchen & Dining", "A composed kitchen with tactile finishes, clear flow and a generous dining connection.", "/media/home/selected-kitchen.jpeg", "50% 50%"], ["The Garden Table", "Residential Interiors", "A softly layered dining room that brings the garden, material warmth and conversation together.", "/media/home/selected-dining.jpeg", "50% 50%"]] as const;

export default function Home() {
  return <main><IntroLoader />
    <header className="site-header"><a href="#top" className="brand">THE LIVING <span>EDIT</span></a><nav><a href="#projects">Projects</a><a href="/studio">Studio</a><a href="/capabilities">Services</a></nav><a href="#quote" className="header-cta">Start a project ↗</a></header>
    <section className="hero" id="top"><Image className="hero-image" src="/media/sections/living-room/image-03.png" alt="Warm living room by The Living Edit" fill loading="eager" sizes="100vw" style={{ objectFit: "cover", objectPosition: "50% 50%", backgroundImage: "none" }} /><div className="hero-shade" /><div className="hero-content"><p className="eyebrow light">Bespoke interiors · Hyderabad</p><h1>Spaces that<br /><i>feel</i> like you.</h1><p>Thoughtful, enduring interiors for the way you live now—and the life you&apos;re growing into.</p><a href="#projects" className="round-link">Discover our work <span>↓</span></a></div><small>The Living Edit<br />Residential design studio</small></section>
    <section className="intro section"><p className="eyebrow">01 · The studio</p><div><h2>We make homes with a sense of <i>ease.</i></h2><p className="lede">The Living Edit is a full-service interior design studio creating calm, characterful homes. We balance beautiful materials with the practical details that make every day better.</p><a className="text-link" href="#studio">Meet the studio <span>→</span></a></div></section>
    <section className="projects section" id="projects"><div className="section-top"><div><p className="eyebrow">02 · Selected work</p><h2>Rooms with a story.</h2></div><a className="text-link" href="/projects">View all projects <span>→</span></a></div><div className="project-grid">{projects.map(([name, category, description, image, position], index) => <article className={`project project-${index + 1}`} key={name}><Image src={image} alt={name} width={1376} height={768} sizes="(max-width: 700px) 86vw, (max-width: 1100px) 55vw, 50vw" loading="lazy" style={{ width: "100%", height: "auto", objectFit: "cover", objectPosition: position }} /><div><h3>{name}</h3><p>{category}</p><small>{description}</small><span>↗</span></div></article>)}<aside className="project-studio-note"><span>The Living Edit</span><b>Material. Light.<br /><i>Life.</i></b><em>01 / 03</em></aside></div></section>
    <section className="statement"><p className="eyebrow">A home should be your favourite place to be.</p><h2>Quiet luxury,<br /><i>made personal.</i></h2></section>
    <DesignModels /><Services capabilities={services.map((service, index) => ({ id: service.slug, title: service.title, slug: service.slug, short_description: service.subtitle, long_description: service.description, icon: null, cover_image_url: null, gallery_urls: [], display_order: index, is_active: true }))} />
    <section className="rooms section" id="services"><div className="section-top"><div><p className="eyebrow">03 · What we design</p><h2>Every room, considered.</h2></div><p className="section-note">From the first sketch to the final cushion, we create a complete, considered home.</p></div><div className="room-grid">{rooms.map(([name, image, position]) => <a className="room" href={`/rooms/${name.toLowerCase().replace(" rooms", "-room").replace("s", "")}`} key={name}><Image src={image} alt={name} width={1376} height={768} sizes="(max-width: 700px) 42vw, 22vw" loading="lazy" style={{ objectFit: "cover", objectPosition: position }} /><div><h3>{name}</h3><span>Explore →</span></div></a>)}</div></section>
    <section className="studio section" id="studio"><Image src="/media/home/selected-commercial.jpeg" alt="Thoughtfully designed commercial interior" width={1376} height={768} sizes="(max-width: 700px) 86vw, 40vw" loading="lazy" style={{ objectFit: "cover", objectPosition: "50% 50%" }} /><div><p className="eyebrow">04 · Our approach</p><h2>Designed around <i>your life.</i></h2><p className="lede">We listen closely, draw with intention, and make each decision with you in mind. The result is a home that is unmistakably yours.</p><div className="numbers"><span><b>01</b>Understand<br />your story</span><span><b>02</b>Shape the<br />vision</span><span><b>03</b>Bring it<br />to life</span></div></div></section>
    <section className="quote-section" id="quote"><div><p className="eyebrow light">05 · Begin your project</p><h2>Let&apos;s create<br />something <i>lasting.</i></h2><p>Tell us a little about your home. We&apos;ll get back to you within two business days.</p><div className="contact"><a href="tel:+910000000000">+91 00000 00000</a><a href="mailto:hello@thelivingedit.in">hello@thelivingedit.in</a><span>Hyderabad, India</span></div></div><QuoteForm /></section>
    <footer><a href="#top" className="brand">THE LIVING <span>EDIT</span></a><p>Timeless interiors for modern living.</p><p>© {new Date().getFullYear()} The Living Edit</p></footer><LuuConsultant />
  </main>;
}
