import { createSupabaseAdminClient } from "@/lib/supabase-server";

export type Project = { id: string; name: string; slug: string; category: string; city: string | null; year: number | null; area: string | null; description: string | null; thumbnail_url: string | null; cover_image_url: string | null; featured: boolean; status: string; display_order: number; services: string[] };
export type Capability = { id: string; title: string; slug: string; short_description: string | null; long_description: string | null; icon: string | null; cover_image_url: string | null; gallery_urls: string[]; display_order: number; is_active: boolean };

export const demoProjects = [
  { id: "demo-terra", name: "The Terra House", slug: "the-terra-house", category: "4 BHK", city: "Jubilee Hills", year: 2025, area: null, description: null, thumbnail_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85", cover_image_url: null, featured: true, status: "published", display_order: 0, services: [] },
  { id: "demo-modern", name: "Quietly Modern", slug: "quietly-modern", category: "3 BHK", city: "Banjara Hills", year: 2025, area: null, description: null, thumbnail_url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=85", cover_image_url: null, featured: true, status: "published", display_order: 1, services: [] },
  { id: "demo-light", name: "A Home in Light", slug: "a-home-in-light", category: "2 BHK", city: "KPHB", year: 2025, area: null, description: null, thumbnail_url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85", cover_image_url: null, featured: true, status: "published", display_order: 2, services: [] },
] satisfies Project[];

export const demoCapabilities = [
  ["Residential interiors", "Homes with warmth, clarity and an unmistakable sense of you."], ["Commercial design", "Purposeful workplaces and hospitality spaces with a memorable point of view."], ["2D planning", "Spatial plans that make every square foot work beautifully."], ["3D visualization", "Detailed material, light and furniture studies before the work begins."], ["AutoCAD documentation", "Precise technical drawings that keep every collaborator aligned."], ["Revit coordination", "Intelligent model-based coordination for complex, considered spaces."], ["3ds Max modelling", "High-fidelity models that let you experience the design in advance."], ["Walkthrough renders", "Cinematic walkthroughs that turn a future space into a felt experience."],
].map(([title, short_description], index) => ({ id: `demo-${index}`, title, slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/,""), short_description, long_description: null, icon: null, cover_image_url: null, gallery_urls: [], display_order: index, is_active: true })) satisfies Capability[];

export async function featuredProjects() { try { const { data } = await createSupabaseAdminClient().from("projects").select("*").eq("status", "published").eq("featured", true).order("display_order").order("created_at", { ascending: false }).limit(3); return data?.length ? data as Project[] : demoProjects; } catch { return demoProjects; } }
export async function publishedProjects() { try { const { data } = await createSupabaseAdminClient().from("projects").select("*").eq("status", "published").order("featured", { ascending: false }).order("display_order").order("created_at", { ascending: false }); return data?.length ? data as Project[] : demoProjects; } catch { return demoProjects; } }
export async function activeCapabilities() { try { const { data } = await createSupabaseAdminClient().from("capabilities").select("*").eq("is_active", true).order("display_order"); return data?.length ? data as Capability[] : demoCapabilities; } catch { return demoCapabilities; } }
