export type EditorialPage = { slug: string; title: string; kicker: string; subtitle: string; overview: string; description: string; focus: string[]; benefits: string[]; faqs: { question: string; answer: string }[]; related: string[]; mediaBase: string };
const faqs = [{ question: "When should we begin?", answer: "Early involvement lets the design, technical information and investment work together." }, { question: "Can this be a standalone service?", answer: "Yes. We can support a focused brief or carry it through a complete interior engagement." }, { question: "How are decisions presented?", answer: "We use clear drawings, material studies and visual references before work reaches site." }];
const entry = (slug: string, title: string, kicker: string, subtitle: string, overview: string, description: string, focus: string[], benefits: string[], related: string[]): EditorialPage => ({ slug, title, kicker, subtitle, overview, description, focus, benefits, related, faqs, mediaBase: `/media/${slug}` });

export const services: EditorialPage[] = [
  entry("residential-interiors", "Residential Interiors", "The Living Edit · Homes", "Homes shaped around the rituals, people and quiet details that make everyday life feel effortless.", "A complete residential interior service for apartments, villas and homes being thoughtfully reimagined.", "We begin with how you live, then translate that point of view into plans, furniture, lighting, finishes and site-ready details. Every room is designed as part of a composed whole that feels practical from day one and more personal over time.", ["Lifestyle and spatial planning", "Custom furniture and storage", "Lighting, material and colour studies", "Execution coordination and styling"], ["A home that supports daily routines", "Clear decisions before site work begins", "A cohesive language across every room", "Fewer costly changes during execution"], ["2D Planning", "3D Visuals & Modeling", "Walkthrough Renders"]),
  entry("commercial-design", "Commercial Design", "The Living Edit · Workplaces", "Spaces that give a brand presence, help teams focus and make every arrival feel considered.", "Commercial environments planned around people, performance and a distinctive brand experience.", "We plan workplaces, boutiques and hospitality spaces with attention to workflow, lighting, acoustic comfort and operational durability. The visual language is developed alongside the practical requirements, so the finished environment feels memorable without losing its purpose.", ["Workplace flow and zoning", "Brand-led customer experience", "Durable materials and operational detail", "Retail, hospitality and office interiors"], ["A clearer journey for staff and visitors", "Design aligned with brand values", "Efficient use of valuable floor area", "Presentation-ready spaces for growth"], ["2D Planning", "Revit Coordination", "Walkthrough Renders"]),
  entry("2d-planning", "2D Planning", "The Living Edit · Planning", "A precise spatial foundation that makes every square foot work beautifully.", "Measured plans and elevations that turn an early idea into a practical, buildable layout.", "We study circulation, furniture clearances, storage, electrical points, ceilings and key elevations in detail. The resulting drawing set gives every collaborator a clear framework for construction and protects the calm of the finished space.", ["Furniture layouts and circulation", "Electrical, lighting and ceiling planning", "Kitchen and wardrobe elevations", "Measured site-ready drawings"], ["Fewer surprises on site", "Better furniture proportions", "Clearer collaboration with contractors", "A stronger basis for budgets"], ["Residential Interiors", "AutoCAD Documentation", "3D Visuals & Modeling"]),
  entry("3d-visuals-modeling", "3D Visuals & Modeling", "The Living Edit · Visualisation", "Rendering, modelling and animation that make every material, light level and spatial decision feel clear before execution.", "Detailed three-dimensional studies for refined interiors, bespoke furniture and cinematic presentation.", "Our rendering and modelling workflow brings a future interior into focus. We build the space, furniture and details in three dimensions, test materials and lighting, then create stills and animation that communicate atmosphere as clearly as dimensions. It is a practical design tool as much as a beautiful presentation.", ["Interior and bespoke furniture modelling", "Material, texture and lighting studies", "Photorealistic renders and visualisation", "Animation and walkthrough-ready scenes"], ["Greater confidence before committing", "More precise material decisions", "A shared vision for every collaborator", "A reusable base for motion and marketing"], ["2D Planning", "SketchUp", "Walkthrough Renders"]),
  entry("autocad-documentation", "AutoCAD Documentation", "The Living Edit · Technical", "Detailed documentation that brings designers, consultants and site teams into alignment.", "A dependable drawing package for interior construction, detailing and coordination.", "Our AutoCAD documentation translates an approved design into plans, elevations, sections, electrical layouts, joinery details and finish schedules. Every drawing is prepared to communicate intent clearly to the people building it.", ["Plans, elevations and sections", "Joinery and furniture detailing", "Electrical and reflected ceiling plans", "Finish and coordination schedules"], ["Less interpretation at site", "A more controlled execution", "Clear trade-to-trade coordination", "Documentation ready for review"], ["2D Planning", "Revit Coordination", "Residential Interiors"]),
  entry("revit-coordination", "Revit Coordination", "The Living Edit · Coordination", "A model-led approach to complex interiors where accuracy and collaboration matter.", "Coordinated Revit models that help resolve interior systems before they reach site.", "Revit gives us a live model of the design, helping coordinate ceilings, services, furniture and architectural constraints in one place. It makes conflicts easier to identify early and keeps complex interior teams working from connected information.", ["Model-based design coordination", "Consultant and services alignment", "Interior component documentation", "Clash-aware design review"], ["Earlier coordination of complex elements", "More reliable information across teams", "A traceable design process", "Better readiness for execution"], ["AutoCAD Documentation", "Commercial Design", "3D Visuals & Modeling"]),
  entry("sketchup", "SketchUp", "The Living Edit · Modelling", "Fast, intuitive spatial studies that make an early interior concept easy to understand and refine.", "SketchUp models that clarify volume, furniture placement and the first spatial decisions.", "We use SketchUp to give early ideas a useful third dimension. It lets us quickly test room proportions, furniture arrangements, joinery volume and sight lines before a concept moves into detailed documentation or photorealistic rendering.", ["Spatial massing and room studies", "Furniture and joinery volume", "Fast concept iterations", "Clear client presentation models"], ["A more intuitive early review", "Faster feedback on layouts", "Clearer proportions before detailing", "A reliable bridge to visualisation"], ["2D Planning", "3D Visuals & Modeling", "Residential Interiors"]),
  entry("walkthrough-renders", "Walkthrough Renders", "The Living Edit · Motion", "A cinematic path through the future space, designed to make decisions feel tangible.", "Narrative walkthrough films for design approvals, stakeholder presentations and launch moments.", "A walkthrough render brings sequence and atmosphere into focus. We choreograph camera movement, styling, materials and light into a film that shows how rooms connect and where their memorable moments live.", ["Cinematic interior walkthroughs", "Lighting and styling direction", "Approval and presentation films", "Marketing-ready motion assets"], ["A more intuitive design review", "Clearer stakeholder presentations", "A compelling record of the vision", "Motion assets ready for launch"], ["3D Visuals & Modeling", "Commercial Design", "Residential Interiors"]),
];

export const rooms: EditorialPage[] = [
  entry("living-room", "Living Rooms", "The Living Edit · Rooms", "Living spaces that make room for conversation, rest and the rituals that bring people together.", "Furniture, lighting and visual calm for the most shared part of the home.", "We plan living rooms around the way people gather, with seating, display, lighting and texture considered as one generous composition.", ["Conversation-led furniture planning", "Feature walls and TV units", "Layered ambient and task lighting", "Styling and display"], ["Comfortable everyday seating", "A calmer visual focal point", "Lighting for different hours", "A room that welcomes guests"], ["Kitchen", "Bedroom", "Residential Interiors"]),
  entry("kitchen", "Kitchens", "The Living Edit · Rooms", "Beautifully organised kitchens that make preparation, storage and gathering feel effortless.", "Kitchen design that balances workflow, durable finishes and the rituals of home cooking.", "We consider the work triangle, prep zones, appliance locations and the connection between cooking and dining, then select cabinetry, hardware and lighting that work beautifully every day.", ["Layouts, islands and workflow", "Cabinetry and pantry strategy", "Countertops, hardware and appliances", "Dining integration and lighting"], ["A more efficient daily routine", "Storage designed around your habits", "Long-lasting material choices", "A welcoming connection to dining"], ["Living Rooms", "2D Planning", "Residential Interiors"]),
  entry("bedroom", "Bedrooms", "The Living Edit · Rooms", "Private rooms designed for deep rest, easy storage and a mood that feels distinctly yours.", "Bedroom interiors resolved around comfort, quiet function and a personal sense of retreat.", "We balance wardrobe storage, bedside function, softened acoustics and adaptable lighting so the room feels restorative at every scale.", ["Wardrobes and concealed storage", "Mood lighting and acoustics", "Comfort-led furniture planning", "Personal display and detail"], ["A more restful environment", "Storage without visual clutter", "Lighting that adapts to routine", "A personal, enduring mood"], ["Living Rooms", "Bathroom", "Residential Interiors"]),
  entry("bathroom", "Bathrooms", "The Living Edit · Rooms", "Practical, restorative bathrooms where technical detail becomes a daily luxury.", "Bathroom interiors designed around comfort, water performance, safety and tactile materiality.", "We bring together wet and dry zoning, storage, lighting, tile layouts and fittings to make daily routines feel intuitive and quietly refined.", ["Wet and dry zoning", "Vanities, niches and storage", "Tiles, fittings and lighting", "Ventilation, safety and durability"], ["A cleaner, more intuitive layout", "Materials selected for longevity", "Better lighting for daily routines", "Spa-like comfort without sacrificing function"], ["Bedroom", "Kitchen", "2D Planning"]),
];
export function getEditorialPage(group: "services" | "rooms", slug: string) { return (group === "services" ? services : rooms).find((item) => item.slug === slug); }
