const section = (slug: string, images: string[]) => images.map((image) => `/media/sections/${slug}/${image}`);
const video = (slug: string, files: string[]) => files.map((file) => `/media/sections/${slug}/${file}`);
export const serviceMedia: Record<string, string[]> = {
  "residential-interiors": section("residential-interiors", ["image-01.jpeg", "image-02.jpeg", "image-03.jpeg"]),
  "commercial-design": section("commercial-design", ["image-01.jpeg", "image-02.jpeg", "image-03.jpeg", "image-04.jpeg"]),
  "2d-planning": section("2d-planning", ["image-01.jpeg", "image-02.jpeg", "image-03.jpeg", "image-04.jpeg", "image-05.jpeg"]),
  "3d-visuals-modeling": section("3d-visuals-modeling", ["image-01.jpeg", "image-02.jpeg", "image-03.jpeg"]),
  "autocad-documentation": section("autocad-documentation", ["image-01.jpeg", "image-02.jpeg"]),
  "revit-coordination": section("revit-coordination", ["image-01.jpeg", "image-02.jpeg"]),
  sketchup: section("sketchup", ["image-01.png", "image-02.png", "image-03.png", "image-04.png", "image-05.png"]),
  "walkthrough-renders": section("walkthrough-renders", ["image-01.jpeg", "image-02.jpeg"]),
  "living-room": section("living-room", ["image-01.png", "image-02.png", "image-03.png", "image-04.png"]), kitchen: section("kitchen", ["image-01.png", "image-02.png", "image-03.png", "image-04.png"]), bedroom: section("bedroom", ["image-01.png", "image-02.png", "image-03.png", "image-04.png"]), bathroom: section("bathroom", ["image-01.jpeg", "image-02.jpeg"]),
};
export const videoMedia: Record<string, string[]> = {
  "residential-interiors": video("residential-interiors", ["video-01.mp4"]), "commercial-design": video("commercial-design", ["video-01.mp4"]), "2d-planning": video("2d-planning", ["video-01.mp4"]), "3d-visuals-modeling": video("3d-visuals-modeling", ["video-01.mp4"]), "autocad-documentation": video("autocad-documentation", ["video-01.mp4"]), "revit-coordination": video("revit-coordination", ["video-01.mp4"]), sketchup: video("sketchup", ["video-01.mp4"]), "walkthrough-renders": video("walkthrough-renders", ["video-01.mp4", "video-02.mp4"]), "living-room": video("living-room", ["video-01.mp4"]), kitchen: video("kitchen", ["video-01.mp4"]), bedroom: video("bedroom", ["video-01.mp4"]), bathroom: video("bathroom", ["video-01.mp4"]),
};
export const portfolioProjects = [["The Walnut Media Lounge", "Living Room", "A warm media wall composition balancing timber, ambient lighting and comfortable seating for unhurried evenings.", "/media/projects/atelier-living.png", "50% 50%"], ["The Conversation Lounge", "Living Room", "A low, relaxed seating plan with sculptural furniture and an atmosphere designed for gathering.", "/media/projects/crafted-kitchen.png", "50% 50%"], ["The Temple Dining Room", "Dining & Pooja", "A bright dining setting where a contemporary table and a detailed feature wall give daily rituals a focal point.", "/media/projects/soft-retreat.png", "50% 42%"], ["The Soft Neutral Suite", "Residential Interior", "A calm, warm-toned room defined by controlled lighting, tactile surfaces and tailored proportions.", "/media/projects/material-study.png", "50% 50%"], ["The Reading Corner", "Residential Detail", "An intimate corner composed with expressive upholstery, a softened palette and just enough light for a pause.", "/media/projects/quiet-corner.png", "50% 50%"], ["The Garden Table", "Dining Room", "A naturally lit dining room where carefully layered materials make entertaining feel easy.", "/media/projects/dining-detail.png", "50% 50%"], ["The Velvet Accent", "Furniture Detail", "A sculptural chair chosen for its silhouette, material honesty and the sense of character it brings to a room.", "/media/projects/heirloom-chair.jpeg", "50% 50%"], ["The Crafted Desk", "Furniture Detail", "A detailed wood piece that celebrates grain, carving and quiet utility.", "/media/projects/heirloom-desk.jpeg", "50% 50%"]] as const;
